# Dataset Overview

The dataset used in this study is obtained from **PJM Interconnection LLC (PJM)**, a regional transmission organization (RTO) in the United States. PJM operates an electric transmission system serving all or parts of the following regions:



- Delaware
- Illinois
- Indiana
- Kentucky
- Maryland
- Michigan
- New Jersey
- North Carolina
- Ohio
- Pennsylvania
- Tennessee
- Virginia
- West Virginia
- District of Columbia

The hourly power consumption data, measured in megawatts (MW), is sourced from PJM's official website. This study focuses on **PJM East**, which provides data spanning from 2002 to 2018 for the entire eastern region.

### Dataset Description

The dataset includes the following columns:

- **Datetime**: The timestamp of the energy consumption measurement (in hourly intervals).
- **PJME_MW**: The energy consumption in megawatts (MW) for the PJM East region at the given timestamp.

### Key Statistics

- **Total Observations**: 145,366 hourly records.
- **Time Period**: 2002 to 2018.

### Data Preprocessing

The dataset has been cleaned and preprocessed to address missing values and ensure consistency, making it suitable for time series analysis and forecasting.

---

# Exploratory Data Analysis (EDA)

This section explores the **PJM East energy consumption dataset** to understand its:

- Distribution
- Trends (there no trend or volatily in our time serie data)
- Patterns over time

The EDA serves as a foundation for identifying key insights and preparing the data for further modeling and forecasting tasks.

In [1]:
import pandas as pd 
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import warnings
import seaborn as sns
import matplotlib.patches as patches
color_pal = sns.color_palette()
plt.style.use('fivethirtyeight')
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 10)


warnings.filterwarnings("ignore")

In [7]:
df = pd.read_csv('PJME_hourly.csv')
display(df.info())
df = df.set_index('Datetime')
#transforming data into datetime type
df.index = pd.to_datetime(df.index)
df = df.sort_index()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145366 entries, 0 to 145365
Data columns (total 2 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Datetime  145366 non-null  object
 1   PJME_MW   145366 non-null  float64
dtypes: float64(1), object(1)
memory usage: 2.2+ MB

None

In [ ]:
def create_hour_month_year(df):

    df = df.copy()
    df['hour'] = df.index.hour     
    df['month'] = df.index.month    
    df['year'] = df.index.year      
    df['dayofmonth'] = df.index.day 
    
    return df

data = create_hour_month_year(df) # We will use it after in the modelisation
data.head()

                     PJME_MW  hour  month  year  dayofmonth
Datetime
2002-01-01 01:00:00  30393.0     1      1  2002           1
2002-01-01 02:00:00  29265.0     2      1  2002           1
2002-01-01 03:00:00  28357.0     3      1  2002           1
2002-01-01 04:00:00  27899.0     4      1  2002           1
2002-01-01 05:00:00  28057.0     5      1  2002           1

In [12]:
print(df.shape)
print(df.isnull().sum())
df.head()

(145366, 1)
PJME_MW    0
dtype: int64

                     PJME_MW
Datetime
2002-01-01 01:00:00  30393.0
2002-01-01 02:00:00  29265.0
2002-01-01 03:00:00  28357.0
2002-01-01 04:00:00  27899.0
2002-01-01 05:00:00  28057.0